// High-level model types for each database table.
// `*Record` types represent raw DB rows generated by Prisma.
// Classes like `User`, `Job`, `Application` are the domain models
// you should import in application code.

import type {
  aboutModel,
  about_statsModel,
  admin_usersModel,
  application_work_sessionsModel,
  applicationsModel,
  branchesModel,
  business_profilesModel,
  client_reviewsModel,
  contactModel,
  employee_profilesModel,
  experiencesModel,
  faqModel,
  faq_sectionModel,
  heroModel,
  hero_trust_itemsModel,
  job_categoriesModel,
  jobsModel,
  mediaModel,
  process_sectionModel,
  process_stepsModel,
  raioaneModel,
  ratingsModel,
  reviewsModel,
  servicesModel,
  services_sectionModel,
  settingsModel,
  testimonialsModel,
  testimonials_sectionModel,
  usersModel,
  why_usModel,
  why_us_itemsModel,
} from "../generated/prisma/models";

export type AboutRecord = aboutModel;
export type AboutStatRecord = about_statsModel;
export type AdminUserRecord = admin_usersModel;
export type ApplicationWorkSessionRecord = application_work_sessionsModel;
export type ApplicationRecord = applicationsModel;
export type BranchRecord = branchesModel;
export type BusinessProfileRecord = business_profilesModel;
export type ClientReviewRecord = client_reviewsModel;
export type ContactRecord = contactModel;
export type EmployeeProfileRecord = employee_profilesModel;
export type ExperienceRecord = experiencesModel;
export type FaqRecord = faqModel;
export type FaqSectionRecord = faq_sectionModel;
export type HeroRecord = heroModel;
export type HeroTrustItemRecord = hero_trust_itemsModel;
export type JobCategoryRecord = job_categoriesModel;
export type JobRecord = jobsModel;
export type MediaRecord = mediaModel;
export type ProcessSectionRecord = process_sectionModel;
export type ProcessStepRecord = process_stepsModel;
export type RaionRecord = raioaneModel;
export type RatingRecord = ratingsModel;
export type ReviewRecord = reviewsModel;
export type ServiceRecord = servicesModel;
export type ServiceSectionRecord = services_sectionModel;
export type SettingRecord = settingsModel;
export type TestimonialRecord = testimonialsModel;
export type TestimonialSectionRecord = testimonials_sectionModel;
export type UserRecord = usersModel;
export type WhyUsRecord = why_usModel;
export type WhyUsItemRecord = why_us_itemsModel;

export { About } from "./About";
export { AboutStat } from "./AboutStat";
export { AdminUser } from "./AdminUser";
export { ApplicationWorkSession } from "./ApplicationWorkSession";
export { Application } from "./Application";
export { Branch } from "./Branch";
export { BusinessProfile } from "./BusinessProfile";
export { ClientReview } from "./ClientReview";
export { Contact } from "./Contact";
export { EmployeeProfile } from "./EmployeeProfile";
export { Experience } from "./Experience";
export { Faq } from "./Faq";
export { FaqSection } from "./FaqSection";
export { Hero } from "./Hero";
export { HeroTrustItem } from "./HeroTrustItem";
export { JobCategory } from "./JobCategory";
export { Job } from "./Job";
export { Media } from "./Media";
export { ProcessSection } from "./ProcessSection";
export { ProcessStep } from "./ProcessStep";
export { Raion } from "./Raion";
export { Rating } from "./Rating";
export { Review } from "./Review";
export { Service } from "./Service";
export { ServiceSection } from "./ServiceSection";
export { Setting } from "./Setting";
export { Testimonial } from "./Testimonial";
export { TestimonialSection } from "./TestimonialSection";
export { User } from "./User";
export { WhyUs } from "./WhyUs";
export { WhyUsItem } from "./WhyUsItem";

